package com.android.cellbroadcastservice;

/* This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int additional_cell_broadcast_receiver_packages = 2130771968;
        public static final int area_info_channels = 2130771969;
        public static final int config_area_info_receiver_packages = 2130771970;
        public static final int test_cell_broadcast_receiver_packages = 2130771971;
    }

    public static final class bool {
        public static final int config_sms_utf8_support = 2130837504;
        public static final int duplicate_compare_body = 2130837505;
        public static final int reset_on_power_cycle_or_airplane_mode = 2130837506;
    }

    public static final class integer {
        public static final int max_location_waiting_time = 2130903040;
        public static final int message_expiration_time = 2130903041;
    }

    public static final class string {
        public static final int etws_primary_default_message_earthquake = 2130968576;
        public static final int etws_primary_default_message_earthquake_and_tsunami = 2130968577;
        public static final int etws_primary_default_message_others = 2130968578;
        public static final int etws_primary_default_message_test = 2130968579;
        public static final int etws_primary_default_message_tsunami = 2130968580;
    }
}
